# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splashScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(500, 500)
        SplashScreen.setMinimumSize(QtCore.QSize(500, 500))
        SplashScreen.setMaximumSize(QtCore.QSize(500, 500))
        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.base = QtWidgets.QFrame(self.centralwidget)
        self.base.setStyleSheet("QFrame {\n"
"    background-color: #26495c;\n"
"    border-radius: 55px;\n"
"}")
        self.base.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.base.setFrameShadow(QtWidgets.QFrame.Raised)
        self.base.setObjectName("base")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.base)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBar = QtWidgets.QFrame(self.base)
        self.progressBar.setMinimumSize(QtCore.QSize(250, 250))
        self.progressBar.setMaximumSize(QtCore.QSize(250, 250))
        self.progressBar.setStyleSheet("QFrame {\n"
"    border-radius: 125px;\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.748 rgba(0, 0, 0, 0), stop:0.75 rgba(229, 229, 220, 255));\n"
"}")
        self.progressBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progressBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.progressBar)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.progressBar)
        self.frame.setMinimumSize(QtCore.QSize(230, 230))
        self.frame.setMaximumSize(QtCore.QSize(230, 230))
        self.frame.setStyleSheet("QFrame {\n"
"    border-radius: 115px;\n"
"    background-color: #26495c;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(200, 100))
        self.label.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.horizontalLayout_3.addWidget(self.frame)
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.horizontalLayout.addWidget(self.base)
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "MainWindow"))
        self.label.setText(_translate("SplashScreen", "0 %"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SplashScreen = QtWidgets.QMainWindow()
    ui = Ui_SplashScreen()
    ui.setupUi(SplashScreen)
    SplashScreen.show()
    sys.exit(app.exec_())
