# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from sources import resource
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 400)
        MainWindow.setMinimumSize(QtCore.QSize(500, 400))
        MainWindow.setMaximumSize(QtCore.QSize(500, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_1 = QtWidgets.QFrame(self.page_1)
        self.frame_1.setStyleSheet("QFrame{\n"
"    border-radius: 25px;\n"
"    background-color: rgb(255, 85, 0);\n"
"}")
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.verticalLayout_2.addWidget(self.frame_1)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.page_2)
        self.frame_2.setStyleSheet("QFrame{\n"
"    border-radius: 25px;\n"
"    background-color: rgb(255, 85, 150);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.page_3)
        self.frame_3.setStyleSheet("QFrame{\n"
"    border-radius: 25px;\n"
"    background-color: rgb(255, 105, 100);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.page_4)
        self.frame_4.setStyleSheet("QFrame{\n"
"    border-radius: 25px;\n"
"    background-color: rgb(255, 225, 100);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5.addWidget(self.frame_4)
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.buttons = QtWidgets.QFrame(self.centralwidget)
        self.buttons.setMinimumSize(QtCore.QSize(0, 50))
        self.buttons.setMaximumSize(QtCore.QSize(16777215, 50))
        self.buttons.setStyleSheet("QFrame{\n"
"    padding: 5px;\n"
"}")
        self.buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons.setObjectName("buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttons)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LBtn = QtWidgets.QPushButton(self.buttons)
        self.LBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.LBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.LBtn.setStyleSheet("QPushButton{\n"
"    border-radius: 20px;\n"
"    background-color: rgba(255, 85, 255, 100);\n"
"    image: url(:/Buttons/previous.png);\n"
"}\n"
"\n"
"QPushButton:pressed{    \n"
"    background-color: rgb(255, 85, 255);\n"
"}")
        self.LBtn.setText("")
        self.LBtn.setObjectName("LBtn")
        self.horizontalLayout.addWidget(self.LBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.RBtn = QtWidgets.QPushButton(self.buttons)
        self.RBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.RBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.RBtn.setStyleSheet("QPushButton{\n"
"    border-radius: 20px;\n"
"    background-color: rgba(255, 85, 255, 100);\n"
"    image: url(:/Buttons/next-button.png);\n"
"}\n"
"\n"
"QPushButton:pressed{    \n"
"    background-color: rgb(255, 85, 255);\n"
"}")
        self.RBtn.setText("")
        self.RBtn.setObjectName("RBtn")
        self.horizontalLayout.addWidget(self.RBtn)
        self.verticalLayout.addWidget(self.buttons)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # All Buttons Connections
        self.LBtn.clicked.connect(lambda: self.LBtnPressed())
        self.RBtn.clicked.connect(lambda: self.RBtnPressed())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    def LBtnPressed(self):
        curN = self.stackedWidget.currentIndex()
        if curN == 0:
            self.stackedWidget.setCurrentIndex(3)
        elif curN == 3:
            self.stackedWidget.setCurrentIndex(curN - 1)
        else:
            self.stackedWidget.setCurrentIndex(curN - 1)

    def RBtnPressed(self):
        curN = self.stackedWidget.currentIndex()
        if curN == 0:
            self.stackedWidget.setCurrentIndex(curN + 1)
        elif curN == 3:
            self.stackedWidget.setCurrentIndex(0)
        else:
            self.stackedWidget.setCurrentIndex(curN + 1)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    win = Ui_MainWindow()
    win.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
